### ISSUE TITLE
Display formatted link to the WQS query map under the map frame

### ISSUE THREAD

**Issue by VojtechDostal** [urbanecm/wikinity#4]
It would be cool if you could display a link (URL) of the specific query that was just searched. The link can be displayed eg. under the map.

**Comment by urbanecm** [comment]
See the screenshot below. I can see there a link to the Wikidata Query interface, in this case [[1]](https://query.wikidata.org/#%23defaultView%3AMap%0ASELECT%20distinct%20%3Fitem%20%3FitemLabel%20%3Fcoord%20%3Flayer%0AWHERE%0A%7B%0A%20%20wd%3AQ1085%20wdt%3AP625%20%3Floc%20.%0A%20%20SERVICE%20wikibase%3Aaround%20%7B%20%0A%20%20%20%20%20%20%3Fitem%20wdt%3AP625%20%3Fcoord%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Acenter%20%3Floc%20.%20%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aradius%20%225%22%20.%20%0A%20%20%7D%20%0A%20%20%0A%20%20OPTIONAL%20%7B%0A%20%20%7B%3Fitem%20p%3AP31/ps%3AP31%2A/wdt%3AP279%2A%20wd%3AQ44539%20.%20%7D%20UNION%20%7B%3Fitem%20p%3AP31/ps%3AP31/wdt%3AP279%2A%20wd%3AQ3947%20.%20%7D%20%0A%20%20BIND%28%22dal%C5%A1%C3%AD%20budovy%22%20AS%20%3Flayer%29%7D%0A%0A%20%20OPTIONAL%20%7B%0A%20%20%3Fitem%20wdt%3AP1435%20wd%3AQ385405%20.%0A%20%20BIND%28%22kulturn%C3%AD%20pam%C3%A1tky%22%20AS%20%3Flayer%29%7D%0A%20%20%0A%20%20OPTIONAL%20%7B%0A%20%20%3Fitem%20wdt%3AP677%20%3Fkod%20.%0A%20%20MINUS%20%7B%3Fitem%20wdt%3AP31%20wd%3AQ811534%20.%7D%0A%20%20BIND%28%22chr%C3%A1n%C4%9Bn%C3%A1%20%C3%BAzem%C3%AD%22%20AS%20%3Flayer%29%7D%0A%20%20%0A%20%20OPTIONAL%20%7B%0A%20%20%3Fitem%20wdt%3AP677%20%3Fkod%20.%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ811534%20.%0A%20%20BIND%28%22pam%C3%A1tn%C3%A9%20stromy%22%20AS%20%3Flayer%29%7D%0A%20%20%0A%20%20OPTIONAL%20%7B%0A%20%20%3Fitem%20p%3AP31/ps%3AP31/wdt%3AP279%20wd%3AQ486972%20.%0A%20%20BIND%28%22s%C3%ADdla%22%20AS%20%3Flayer%29%7D%0A%20%0A%20%20OPTIONAL%20%7B%0A%20%20%3Fitem%20p%3AP31/ps%3AP31/wdt%3AP279%2A%20wd%3AQ15893266%20.%0A%20%20BIND%28%22zanikl%C3%A9%20objekty%22%20AS%20%3Flayer%29%7D%0A%20%20%0A%20%20MINUS%20%7B%3Fitem%20wdt%3AP18%20%3Fimg%20.%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22cs%22%20.%20%7D%20%20%0A%20%20%0A%7D%0A)

![wikinity](https://cloud.githubusercontent.com/assets/10050467/24916976/07cf485c-1edc-11e7-9947-0e615cd75d0d.png)

**Comment by VojtechDostal** [comment]
Right! Then it's settled :-)

**Comment by urbanecm** [comment]
Yeah. BTW it was there before you opened the issue ;).
